schema_version = "1.0.0"

# 唯一扩展 ID，建议小写蛇形命名
id = "aartflow_blender"

# 扩展基本信息
name = "AartFlow"
version = "1.0.1"
tagline = "Modular Blender add-on integration system"
type = "add-on"

# 兼容的 Blender 版本范围
blender_version_min = "4.2.0"
blender_version_max = "4.7.0"

# 维护者与项目链接
maintainers = ["yizhww <yzh_1234@qq.com>"]
maintainer = "yizhww <yzh_1234@qq.com>"
website = "https://github.com/yizhww/AartFlow_blender"
issue_tracker = "https://github.com/yizhww/AartFlow_blender/issues"

# 许可证与标签（使用 SPDX 标识）
license = ["SPDX:GPL-3.0-or-later"]
tags = ["3D View", "Render", "User Interface", "Measurement", "Visualization"]


